import {it,expect} from 'vitest'
import {compareJson} from '../src/tools/json-diff/core'
it('ignores object ordering recursively',()=>expect(compareJson('{"b":{"x":1,"y":2},"a":0}','{"a":0,"b":{"y":2,"x":1}}')).toEqual([]))
it('name values and missing type original ranges',()=>{const l='{"name":"张三","type":"user"}',r='{"name":"李四"}';const d=compareJson(l,r);expect(d.map(x=>[x.path,x.kind])).toEqual([['$["name"]','value'],['$["type"]','missing-right']]);expect(l.slice(d[0]!.left!.from,d[0]!.left!.to)).toBe('"张三"');expect(l.slice(d[1]!.left!.from,d[1]!.left!.to)).toBe('"type":"user"');expect(d[1]!.right).toBeUndefined()})
it('missing distinct from null',()=>expect(compareJson('{}','{"type":null}')[0]!.kind).toBe('missing-left'))
it('types matter',()=>expect(compareJson('{"x":1}','{"x":"1"}')[0]!.kind).toBe('type'))
it('array position matters',()=>expect(compareJson('[1,2]','[2,1]')).toHaveLength(2))
it('array length',()=>expect(compareJson('[1]','[1,null]')[0]!.path).toBe('$[1]'))
it('large integers distinct',()=>expect(compareJson('9007199254740992','9007199254740993')).toHaveLength(1))
for(const [a,b] of [['1','1.0'],['1000','1e3'],['-0','0'],['0.00100','1e-3'],['1e999999','10e999998'],['-12.30','-123e-1']])it('equal numbers '+a,()=>expect(compareJson(a!,b!)).toEqual([]))
it('escaped string value equality',()=>expect(compareJson('"a"','"\\u0061"')).toEqual([]))
it('paths escape keys',()=>expect(compareJson('{"a.b":1}','{"a.b":2}')[0]!.path).toBe('$["a.b"]'))
it('prototype key',()=>expect(compareJson('{"__proto__":1}','{"__proto__":2}')).toHaveLength(1))
it('container type only one diff',()=>expect(compareJson('{"a":[1,2]}','{"a":{}}')).toHaveLength(1))
it('CRLF ranges',()=>{const l='{\r\n"x":"😀"\r\n}';const d=compareJson(l,'{"x":"y"}')[0]!;expect(l.slice(d.left!.from,d.left!.to)).toBe('"😀"')})
for(const bad of ['{"a":1,"a":2}','{"a":1,"\\u0061":2}','[1,]','undefined',''])it('reject '+bad,()=>expect(()=>compareJson(bad,'{}')).toThrow('左侧'))
it('right errors named',()=>expect(()=>compareJson('{}','{')).toThrow('右侧'))
it('size cap',()=>expect(()=>compareJson(' '.repeat(1024*1024)+'{}','{}')).toThrow())
it('diff cap',()=>expect(()=>compareJson(JSON.stringify(Array(2001).fill(1)),JSON.stringify(Array(2001).fill(2)))).toThrow('2000'))
